[build]
  command = "pnpm install && pnpm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.18.0"
  PNPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
